services:
  vika_bot:
    build: .
    container_name: vika_bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: vika_qdrant
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "127.0.0.1:6333:6333"

volumes:
  qdrant_data:
